### ISSUE TITLE
Crashlytics NinchatQueueActivity.java line 69 (124/39)

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#101]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fi.hiq.terveystalo/com.ninchat.sdk.activities.NinchatQueueActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Spanned com.ninchat.sdk.NinchatSessionManager.getQueueMessage()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Spanned com.ninchat.sdk.NinchatSessionManager.getQueueMessage()' on a null object reference
       at com.ninchat.sdk.activities.NinchatQueueActivity.onCreate(NinchatQueueActivity.java:69)
       at android.app.Activity.performCreate(Activity.java:7815)
       at android.app.Activity.performCreate(Activity.java:7804)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Toni-** [comment]
Same as #74
