### ISSUE TITLE
Crashlytics NinchatActivity.java line 10  (74/39)

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#102]
NinchatActivity.java line 10
com.ninchat.sdk.activities.NinchatActivity.setQueueAdapter

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fi.hiq.terveystalo/com.ninchat.sdk.activities.NinchatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
       at com.ninchat.sdk.activities.NinchatActivity.setQueueAdapter(NinchatActivity.java:10)
       at com.ninchat.sdk.activities.NinchatActivity.onCreate(NinchatActivity.java:52)
       at android.app.Activity.performCreate(Activity.java:7458)
       at android.app.Activity.performCreate(Activity.java:7448)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Toni-** [comment]
SessionManager null object reference is related to #74
