### ISSUE TITLE
Crashlytics NinchatQueueActivity.java (28/12)

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#104]
NinchatQueueActivity.java
com.ninchat.sdk.activities.NinchatQueueActivity.onCreate

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{fi.hiq.terveystalo/com.ninchat.sdk.activities.NinchatQueueActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Spanned com.ninchat.sdk.NinchatSessionManager.getQueueMessage()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Spanned com.ninchat.sdk.NinchatSessionManager.getQueueMessage()' on a null object reference
       at com.ninchat.sdk.activities.NinchatQueueActivity.onCreate(NinchatQueueActivity.java)
       at android.app.Activity.performCreate(Activity.java:6915)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:156)
       at android.app.ActivityThread.main(ActivityThread.java:6517)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by Toni-** [comment]
Same as #74
