### ISSUE TITLE
Test app crash with index out of bounds exception

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#47]
Google Pixel emulator Android 7.0 SDK 0.2.6

First customer sent two messages and when agent sent one the app crashed with the following error. Funny thing was that agent didn't see any name for the customer.
<img width="564" alt="screenshot 2018-12-13 at 12 47 13" src="https://user-images.githubusercontent.com/1185899/49933829-61607280-fed5-11e8-90bb-ecc67de8ce4a.png">

2018-12-12 10:10:07.747 2552-2700/? E/NinchatSessionManager: Failed to get the event from map[action_id:4 event:message_received message_user_id:64o9ll1k00e8 message_user_name:Asiakas channel_id:64o9lt7e00e8 message_id:64o9m9au00e8 message_time:1.544602208e+09 message_type:ninchat.com/text event_id:7 frames:1]
    java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.ArrayList.listIterator(ArrayList.java:782)
        at com.ninchat.sdk.adapters.NinchatMessageAdapter.add(NinchatMessageAdapter.java:236)
        at com.ninchat.sdk.NinchatSessionManager.messageReceived(NinchatSessionManager.java:668)
        at com.ninchat.sdk.NinchatSessionManager.access$400(NinchatSessionManager.java:63)
        at com.ninchat.sdk.NinchatSessionManager$3.onEvent(NinchatSessionManager.java:279)
2018-12-12 10:18:43.698 2552-3496/? E/NinchatSessionManager: Failed to get the event from map[message_user_name:Antti message_id:64oa616v00e8 message_type:ninchat.com/text message_user_id:02eobjtj event_id:5 frames:1 channel_id:64oa5u2t00e8 event:message_received message_time:1.544602724e+09]
    java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.ArrayList.listIterator(ArrayList.java:782)
        at com.ninchat.sdk.adapters.NinchatMessageAdapter.add(NinchatMessageAdapter.java:236)
        at com.ninchat.sdk.NinchatSessionManager.messageReceived(NinchatSessionManager.java:668)
        at com.ninchat.sdk.NinchatSessionManager.access$400(NinchatSessionManager.java:63)
        at com.ninchat.sdk.NinchatSessionManager$3.onEvent(NinchatSessionManager.java:279)
2018-12-12 10:18:43.784 2552-3496/? E/NinchatSessionManager: Failed to get the event from map[channel_id:64oa5u2t00e8 event:channel_member_updated member_attrs:map[operator:true since:1.544602721e+09] user_id:02eobjtj event_id:6]
    java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.ArrayList.listIterator(ArrayList.java:782)
        at com.ninchat.sdk.adapters.NinchatMessageAdapter.removeWritingMessage(NinchatMessageAdapter.java:264)
        at com.ninchat.sdk.NinchatSessionManager.memberUpdated(NinchatSessionManager.java:763)
        at com.ninchat.sdk.NinchatSessionManager.access$700(NinchatSessionManager.java:63)
        at com.ninchat.sdk.NinchatSessionManager$3.onEvent(NinchatSessionManager.java:285)
2018-12-12 10:18:58.858 2552-3496/? E/NinchatSessionManager: Failed to get the event from map[message_type:ninchat.com/text event_id:9 event:message_received message_id:64oa6g0400jk4 message_time:1.544602739e+09 message_user_name:Asiakas frames:1 action_id:4 channel_id:64oa5u2t00e8 message_user_id:64oa5k9j00jk4]
    java.lang.IndexOutOfBoundsException: Index: -1
        at java.util.ArrayList.listIterator(ArrayList.java:782)
        at com.ninchat.sdk.adapters.NinchatMessageAdapter.add(NinchatMessageAdapter.java:236)
        at com.ninchat.sdk.NinchatSessionManager.messageReceived(NinchatSessionManager.java:668)
        at com.ninchat.sdk.NinchatSessionManager.access$400(NinchatSessionManager.java:63)
        at com.ninchat.sdk.NinchatSessionManager$3.onEvent(NinchatSessionManager.java:279)
2018-12-12 10:20:11.417 2552-2552/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ninchat.sdktestapp, PID: 2552
    java.lang.IndexOutOfBoundsException: Index: -1, Size: 0
        at java.util.ArrayList.add(ArrayList.java:457)
        at com.ninchat.sdk.adapters.NinchatMessageAdapter.close(NinchatMessageAdapter.java:297)
        at com.ninchat.sdk.activities.NinchatChatActivity$1.onReceive(NinchatChatActivity.java:135)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
2018-12-12 10:25:11.656 1613-1815/system_process E/ActivityManager: Found activity ActivityRecord{badb004 u0 com.ninchat.sdktestapp/.MainActivity t7 f} in proc activity list using null instead of expected ProcessRecord{3ab24d6 2552:com.ninchat.sdktestapp/u0a80}
2018-12-13 12:39:42.168 3920-3951/com.ninchat.sdktestapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2018-12-13 12:39:42.168 3920-3951/com.ninchat.sdktestapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2018-12-13 12:40:01.072 3920-4092/com.ninchat.sdktestapp E/GoLog: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
2018-12-13 12:40:01.294 3920-3920/com.ninchat.sdktestapp E/ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
2018-12-13 12:40:01.294 3920-3920/com.ninchat.sdktestapp E/ApkAssets: Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
2018-12-13 12:40:01.385 3920-3920/com.ninchat.sdktestapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2018-12-13 12:40:01.386 3920-3920/com.ninchat.sdktestapp E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2018-12-13 12:45:15.766 3920-3920/com.ninchat.sdktestapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ninchat.sdktestapp, PID: 3920
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{b060028 position=6 id=-1, oldPos=5, pLpos:5 scrap [attachedScrap] tmpDetached no parent} android.support.v7.widget.RecyclerView{eba36e6 VFE...... ......I. 0,669-1080,1517 #7f08006a app:id/message_list}, adapter:com.ninchat.sdk.adapters.NinchatMessageAdapter@de7a427, layout:android.support.v7.widget.LinearLayoutManager@ccef6d4, context:com.ninchat.sdk.activities.NinchatChatActivity@f4be07d
        at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5610)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5792)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:616)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by JussiPekonen-Qvik** [comment]
Haven't been able to reproduce. But let's keep the issue open until we can ensure that this does not pop up again.

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed.
