### ISSUE TITLE
Android 8, Galaxy S8: Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#53]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{ab716b7 position=5 id=-1, oldPos=5, pLpos:-1 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{c58a358 VFE...... ......I. 0,114-1080,1179 #7f08007f app:id/message_list}, adapter:com.ninchat.sdk.adapters.NinchatMessageAdapter@181298e, layout:androidx.recyclerview.widget.LinearLayoutManager@7c25af, context:com.ninchat.sdk.activities.NinchatChatActivity@d56d554
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:119)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:49)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:5)
at androidx.recyclerview.widget.RecyclerView$Recycler.getScrapList(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.hasMore(LinearLayoutManager.java:11)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java:44)
at androidx.recyclerview.widget.LinearLayoutManager.isAutoMeasureEnabled(LinearLayoutManager.java:356)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:202)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:29)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:65)
at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:17)
at android.view.Choreographer$CallbackRecord.run + 1004(Choreographer.java:1004)
at android.view.Choreographer.doCallbacks + 816(Choreographer.java:816)
at android.view.Choreographer.doFrame + 748(Choreographer.java:748)
at android.view.Choreographer$FrameDisplayEventReceiver.run + 990(Choreographer.java:990)
at android.os.Handler.handleCallback + 873(Handler.java:873)
at android.os.Handler.dispatchMessage + 99(Handler.java:99)
at android.os.Looper.loop + 193(Looper.java:193)
at android.app.ActivityThread.main + 6863(ActivityThread.java:6863)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 537(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed.
