### ISSUE TITLE
Android 8, Galaxy S8: Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected.

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#54]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:7).state:7 androidx.recyclerview.widget.RecyclerView{f57499d VFE...... ......ID 0,0-1080,896 #7f08007f app:id/message_list}, adapter:com.ninchat.sdk.adapters.NinchatMessageAdapter@47c5521, layout:androidx.recyclerview.widget.LinearLayoutManager@3667d46, context:com.ninchat.sdk.activities.NinchatChatActivity@8940ac9
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:387)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:5)
at androidx.recyclerview.widget.RecyclerView$Recycler.getScrapList(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.hasMore(LinearLayoutManager.java:11)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java:44)
at androidx.recyclerview.widget.LinearLayoutManager.isAutoMeasureEnabled(LinearLayoutManager.java:356)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:202)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:29)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:93)
at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:17)
at android.view.Choreographer$CallbackRecord.run + 965(Choreographer.java:965)
at android.view.Choreographer.doCallbacks + 777(Choreographer.java:777)
at android.view.Choreographer.doFrame + 706(Choreographer.java:706)
at android.view.Choreographer$FrameDisplayEventReceiver.run + 951(Choreographer.java:951)
at android.os.Handler.handleCallback + 873(Handler.java:873)
at android.os.Handler.dispatchMessage + 99(Handler.java:99)
at android.os.Looper.loop + 193(Looper.java:193)
at android.app.ActivityThread.main + 6715(ActivityThread.java:6715)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main + 911(ZygoteInit.java:911)

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed now.
