### ISSUE TITLE
Android 8, Galaxy S8: Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#55]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{1ff456e position=4 id=-1, oldPos=3, pLpos:3 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{32daeec VFE...... ......I. 0,795-1440,1710 #7f08007f app:id/message_list}, adapter:com.ninchat.sdk.adapters.NinchatMessageAdapter@e769446, layout:androidx.recyclerview.widget.LinearLayoutManager@dcea607, context:com.ninchat.sdk.activities.NinchatChatActivity@b02848
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:119)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:49)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:5)
at androidx.recyclerview.widget.RecyclerView$Recycler.getScrapList(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.hasMore(LinearLayoutManager.java:11)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java:44)
at androidx.recyclerview.widget.LinearLayoutManager.isAutoMeasureEnabled(LinearLayoutManager.java:356)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:202)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:29)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:93)
at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:17)
at android.view.Choreographer$CallbackRecord.run + 949(Choreographer.java:949)
at android.view.Choreographer.doCallbacks + 761(Choreographer.java:761)
at android.view.Choreographer.doFrame + 693(Choreographer.java:693)
at android.view.Choreographer$FrameDisplayEventReceiver.run + 935(Choreographer.java:935)
at android.os.Handler.handleCallback + 873(Handler.java:873)
at android.os.Handler.dispatchMessage + 99(Handler.java:99)
at android.os.Looper.loop + 214(Looper.java:214)
at android.app.ActivityThread.main + 6986(ActivityThread.java:6986)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main + 1445(ZygoteInit.java:1445)

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed now.
