### ISSUE TITLE
Android 8, Galaxy S8: Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 11

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#56]
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 11(offset:12).state:12 androidx.recyclerview.widget.RecyclerView{7a31ab0 VFE...... ......I. 0,0-1080,730 #7f08007f app:id/message_list}, adapter:com.ninchat.sdk.adapters.NinchatMessageAdapter@7baecdf, layout:androidx.recyclerview.widget.LinearLayoutManager@23cfd2c, context:com.ninchat.sdk.activities.NinchatChatActivity@6b39925
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:387)
at androidx.recyclerview.widget.RecyclerView$Recycler.clear(RecyclerView.java:5)
at androidx.recyclerview.widget.RecyclerView$Recycler.getScrapList(RecyclerView.java:1)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.hasMore(LinearLayoutManager.java:11)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java)
at androidx.recyclerview.widget.LinearLayoutManager.generateDefaultLayoutParams(LinearLayoutManager.java:44)
at androidx.recyclerview.widget.LinearLayoutManager.isAutoMeasureEnabled(LinearLayoutManager.java:356)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:202)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:29)
at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:93)
at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:17)
at android.view.Choreographer$CallbackRecord.run + 911(Choreographer.java:911)
at android.view.Choreographer.doCallbacks + 723(Choreographer.java:723)
at android.view.Choreographer.doFrame + 655(Choreographer.java:655)
at android.view.Choreographer$FrameDisplayEventReceiver.run + 897(Choreographer.java:897)
at android.os.Handler.handleCallback + 789(Handler.java:789)
at android.os.Handler.dispatchMessage + 98(Handler.java:98)
at android.os.Looper.loop + 164(Looper.java:164)
at android.app.ActivityThread.main + 6944(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run + 327(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main + 1374(ZygoteInit.java:1374)

**Comment by JussiPekonen-Qvik** [comment]
Should be fixed now.
