### ISSUE TITLE
Crash on HUAWEI P20 Pro Android 9 (0.4.3)

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#71]
Caused by java.lang.IndexOutOfBoundsException: Index: -1
at java.util.ArrayList.listIterator(ArrayList.java:810)
at com.ninchat.sdk.adapters.NinchatMessageAdapter.getLastMessageId(NinchatMessageAdapter.java:8)
at com.ninchat.sdk.activities.NinchatChatActivity.onResume(NinchatChatActivity.java:18)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
at android.app.Activity.performResume(Activity.java:7614)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4412)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
at android.os.Handler.dispatchMessage(Handler.java:112)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7625)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by Toni-** [comment]
Same as #103
