### ISSUE TITLE
0.4.3 Android 8 and 9 java.lang.RuntimeException

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#75]
Fatal Exception: java.lang.RuntimeException
Unable to resume activity {.../com.ninchat.sdk.activities.NinchatChatActivity}: java.lang.IndexOutOfBoundsException: Index: -1
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {.../com.ninchat.sdk.activities.NinchatChatActivity}: java.lang.IndexOutOfBoundsException: Index: -1
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4014)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4046)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7050)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by java.lang.IndexOutOfBoundsException
Index: -1
Caused by java.lang.IndexOutOfBoundsException: Index: -1
at java.util.ArrayList.listIterator(ArrayList.java:810)
at com.ninchat.sdk.adapters.NinchatMessageAdapter.getLastMessageId(NinchatMessageAdapter.java:8)
at com.ninchat.sdk.activities.NinchatChatActivity.onResume(NinchatChatActivity.java:18)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
at android.app.Activity.performResume(Activity.java:7572)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4006)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4046)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7050)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by Toni-** [comment]
Same as #103
