### ISSUE TITLE
0.4.3 Android 8 and 9 unable to start activtity java.lang.RuntimeException

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#76]
Android 9 ja 8.1:

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{.../com.ninchat.sdk.activities.NinchatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{.../com.ninchat.sdk.activities.NinchatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3173)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3284)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7383)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatQueueListAdapter com.ninchat.sdk.NinchatSessionManager.getNinchatQueueListAdapter(android.app.Activity)' on a null object reference
at com.ninchat.sdk.activities.NinchatActivity.setQueueAdapter(NinchatActivity.java:10)
at com.ninchat.sdk.activities.NinchatActivity.onCreate(NinchatActivity.java:52)
at android.app.Activity.performCreate(Activity.java:7358)
at android.app.Activity.performCreate(Activity.java:7349)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3126)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3284)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1894)
at android.os.Handler.dispatchMessage(Handler.java:109)
at android.os.Looper.loop(Looper.java:166)
at android.app.ActivityThread.main(ActivityThread.java:7383)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by Toni-** [comment]
SessionManager null object reference is most likely related to #74
