### ISSUE TITLE
0.4.3 Android 9 Unable to instantiate activity

### ISSUE THREAD

**Issue by plokk** [somia/ninchat-sdk-android#77]
Fatal Exception: java.lang.RuntimeException
Unable to instantiate activity ComponentInfo{.../com.ninchat.sdk.activities.NinchatChatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatMessageAdapter com.ninchat.sdk.NinchatSessionManager.getMessageAdapter()' on a null object reference
Fatal Exception: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{.../com.ninchat.sdk.activities.NinchatChatActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatMessageAdapter com.ninchat.sdk.NinchatSessionManager.getMessageAdapter()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2977)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6898)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatMessageAdapter com.ninchat.sdk.NinchatSessionManager.getMessageAdapter()' on a null object reference
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.ninchat.sdk.adapters.NinchatMessageAdapter com.ninchat.sdk.NinchatSessionManager.getMessageAdapter()' on a null object reference
at com.ninchat.sdk.activities.NinchatChatActivity.<init>(NinchatChatActivity.java:5)
at java.lang.Class.newInstance(Class.java)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java)
at android.app.Instrumentation.newActivity(Instrumentation.java:1232)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6898)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Toni-** [comment]
SessionManager null object reference is most likely related to #74
